-- MAHAMUD EFX Korean Study Master
-- Run this entire file in Supabase SQL Editor after creating the project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  username_normalized text generated always as (lower(username)) stored,
  email text not null,
  role text not null default 'user' check (role in ('user','admin')),
  points bigint not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_username_normalized_uidx
  on public.profiles(username_normalized);

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  exam_title text not null,
  questions integer not null,
  correct integer not null default 0,
  wrong integer not null default 0,
  percentage integer not null default 0,
  duration_seconds integer not null default 0,
  time_used_seconds integer not null default 0,
  points integer not null default 0,
  completed_at timestamptz not null default now()
);

create index if not exists exam_results_user_id_idx on public.exam_results(user_id);
create index if not exists exam_results_completed_at_idx on public.exam_results(completed_at desc);

create or replace function public.mefx_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.mefx_is_admin() to authenticated;

create or replace function public.mefx_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  uname text;
begin
  uname := trim(coalesce(new.raw_user_meta_data->>'username',''));
  if uname !~ '^[A-Za-z0-9_]{3,24}$' then
    raise exception 'Invalid username';
  end if;

  insert into public.profiles(id, username, email)
  values(new.id, uname, lower(new.email));

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.mefx_handle_new_user();

-- Username login resolver. It returns only the authentication email for the
-- requested username. No profile, score, role or password data is exposed.
create or replace function public.mefx_login_email(p_username text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select email from public.profiles
  where username_normalized = lower(trim(p_username))
  limit 1;
$$;

grant execute on function public.mefx_login_email(text) to anon, authenticated;

create or replace function public.mefx_set_result_points()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.questions := greatest(coalesce(new.questions,0),0);
  new.correct := greatest(least(coalesce(new.correct,0),new.questions),0);
  new.wrong := greatest(new.questions-new.correct,0);
  new.percentage := case when new.questions > 0 then round((new.correct::numeric/new.questions::numeric)*100) else 0 end;
  new.points := new.correct * 10;
  return new;
end;
$$;

drop trigger if exists mefx_result_points on public.exam_results;
create trigger mefx_result_points
before insert on public.exam_results
for each row execute procedure public.mefx_set_result_points();

create or replace function public.mefx_award_result_points()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles set points = points + new.points where id = new.user_id;
  return new;
end;
$$;

drop trigger if exists mefx_award_points on public.exam_results;
create trigger mefx_award_points
after insert on public.exam_results
for each row execute procedure public.mefx_award_result_points();

create or replace function public.get_leaderboard(p_limit integer default 100)
returns table(username text, points bigint)
language sql
stable
security definer
set search_path = public
as $$
  select p.username, p.points
  from public.profiles p
  order by p.points desc, p.created_at asc
  limit greatest(1, least(coalesce(p_limit,100),100));
$$;

grant execute on function public.get_leaderboard(integer) to authenticated;

alter table public.profiles enable row level security;
alter table public.exam_results enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin
on public.profiles for select to authenticated
using (id = auth.uid() or public.mefx_is_admin());

drop policy if exists exam_results_insert_self on public.exam_results;
create policy exam_results_insert_self
on public.exam_results for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists exam_results_select_self_or_admin on public.exam_results;
create policy exam_results_select_self_or_admin
on public.exam_results for select to authenticated
using (user_id = auth.uid() or public.mefx_is_admin());

-- IMPORTANT: after your own account is created, replace the username below
-- and run this one line to make yourself the only Admin initially.
-- update public.profiles set role='admin' where username_normalized='mahamud';
